language: python

python:
  - 2.7
  - 3.3
  - pypy

install:
  - pip install --use-mirrors coveralls
  - pip install --use-mirrors -r dev-requirements.txt
  - pip install --use-mirrors -r requirements.txt

script:
  - nosetests -v --with-coverage --cover-package=exifrenamer

after_success:
  - coveralls --verbose
